# -*- coding: utf-8 -*-
"""Classroom_Attendance_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjpGOhTxgl_X1BSf5aIYesVRo3Dufcd2

# 🎓 Classroom Attendance System using Face Recognition

This notebook allows you to:
- Upload student photos (one per student)
- Upload a classroom photo
- Automatically recognize students and mark attendance
- Generate attendance reports with visualizations

---

## 📦 Step 1: Install Required Libraries

This will install face_recognition and other dependencies. **This may take 3-5 minutes.**
"""

# Install required libraries
!apt-get update
!apt-get install -y cmake
!pip install face_recognition
!pip install opencv-python
!pip install pillow

print("\n✅ Installation complete!")

"""## 📚 Step 2: Import Libraries"""

import face_recognition
import cv2
import numpy as np
import os
from datetime import datetime
import csv
from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt
from IPython.display import display, HTML
import pandas as pd

print("✅ All libraries imported successfully!")

"""## 🔧 Step 3: Define Attendance System Class"""

class ClassroomAttendanceSystem:
    def __init__(self):
        """Initialize the attendance system"""
        self.known_face_encodings = []
        self.known_face_names = []
        self.student_images = {}  # Store original images

    def load_student_image(self, image_path, student_name):
        """Load a single student image and create face encoding"""
        try:
            # Load image
            image = face_recognition.load_image_file(image_path)

            # Get face encodings
            encodings = face_recognition.face_encodings(image)

            if len(encodings) > 0:
                self.known_face_encodings.append(encodings[0])
                self.known_face_names.append(student_name)
                self.student_images[student_name] = image
                return True, f"✅ Successfully loaded: {student_name}"
            else:
                return False, f"❌ No face detected in image for: {student_name}"
        except Exception as e:
            return False, f"❌ Error loading {student_name}: {str(e)}"

    def load_all_students(self, uploaded_files):
        """Load all uploaded student images"""
        results = []
        print("\n📸 Loading student images...\n")

        for filename, filepath in uploaded_files.items():
            # Extract student name from filename (remove extension)
            student_name = os.path.splitext(filename)[0].replace('_', ' ')
            success, message = self.load_student_image(filepath, student_name)
            print(message)
            results.append((student_name, success))

        successful = sum(1 for _, success in results if success)
        print(f"\n📊 Summary: {successful}/{len(results)} student(s) loaded successfully")
        return results

    def recognize_classroom(self, classroom_image_path, tolerance=0.6):
        """Recognize students in classroom image"""
        if not self.known_face_encodings:
            return None, "❌ No student data loaded. Please upload student images first."

        print("\n🔍 Analyzing classroom image...")

        # Load classroom image
        classroom_image = face_recognition.load_image_file(classroom_image_path)
        classroom_image_cv = cv2.cvtColor(classroom_image, cv2.COLOR_RGB2BGR)

        # Detect faces
        print("👤 Detecting faces...")
        face_locations = face_recognition.face_locations(classroom_image)
        face_encodings = face_recognition.face_encodings(classroom_image, face_locations)

        print(f"✅ Found {len(face_locations)} face(s) in classroom")

        # Track attendance
        present_students = []
        unknown_faces = 0
        face_details = []

        # Process each detected face
        for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
            # Compare with known faces
            matches = face_recognition.compare_faces(
                self.known_face_encodings, face_encoding, tolerance=tolerance
            )
            name = "Unknown"
            confidence = 0

            # Calculate face distances
            face_distances = face_recognition.face_distance(
                self.known_face_encodings, face_encoding
            )

            if len(face_distances) > 0:
                best_match_index = np.argmin(face_distances)
                if matches[best_match_index]:
                    name = self.known_face_names[best_match_index]
                    confidence = 1 - face_distances[best_match_index]
                    if name not in present_students:
                        present_students.append(name)
                else:
                    unknown_faces += 1
            else:
                unknown_faces += 1

            face_details.append({
                'name': name,
                'confidence': confidence,
                'location': (top, right, bottom, left)
            })

            # Draw on image
            color = (0, 255, 0) if name != "Unknown" else (0, 0, 255)
            cv2.rectangle(classroom_image_cv, (left, top), (right, bottom), color, 2)

            # Add label with background
            label = f"{name} ({confidence:.2%})" if name != "Unknown" else "Unknown"
            cv2.rectangle(classroom_image_cv, (left, bottom - 35), (right, bottom), color, cv2.FILLED)
            cv2.putText(classroom_image_cv, label, (left + 6, bottom - 6),
                       cv2.FONT_HERSHEY_DUPLEX, 0.5, (255, 255, 255), 1)

        # Prepare attendance data
        absent_students = [name for name in self.known_face_names
                          if name not in present_students]

        attendance_data = {
            'date': datetime.now().strftime("%Y-%m-%d"),
            'time': datetime.now().strftime("%H:%M:%S"),
            'total_students': len(self.known_face_names),
            'present': sorted(present_students),
            'absent': sorted(absent_students),
            'present_count': len(present_students),
            'absent_count': len(absent_students),
            'unknown_faces': unknown_faces,
            'face_details': face_details,
            'annotated_image': cv2.cvtColor(classroom_image_cv, cv2.COLOR_BGR2RGB)
        }

        return attendance_data, "✅ Recognition complete!"

    def save_attendance_csv(self, attendance_data, filename="attendance_report.csv"):
        """Save attendance to CSV file"""
        with open(filename, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(['Date', 'Time', 'Student Name', 'Status', 'Confidence'])

            # Write present students
            for detail in attendance_data['face_details']:
                if detail['name'] != 'Unknown':
                    writer.writerow([
                        attendance_data['date'],
                        attendance_data['time'],
                        detail['name'],
                        'Present',
                        f"{detail['confidence']:.2%}"
                    ])

            # Write absent students
            for student in attendance_data['absent']:
                writer.writerow([
                    attendance_data['date'],
                    attendance_data['time'],
                    student,
                    'Absent',
                    'N/A'
                ])

        return filename

print("✅ Attendance system class defined successfully!")

"""## 📤 Step 4: Upload Student Photos

**Instructions:**
1. Click the "Choose Files" button
2. Select photos of students (one photo per student)
3. **Important:** Name your files like: `John_Doe.jpg`, `Jane_Smith.jpg`, etc.
4. Supported formats: `.jpg`, `.jpeg`, `.png`

**Tips:**
- Use clear, front-facing photos
- One face per image
- Good lighting recommended
"""

# Initialize the system
attendance_system = ClassroomAttendanceSystem()

# Create directory for student images
os.makedirs('known_students', exist_ok=True)

print("📤 Please upload student photos...")
print("\nFile naming format: StudentName.jpg (e.g., John_Doe.jpg)\n")

# Upload student images
uploaded = files.upload()

# Save uploaded files
uploaded_files = {}
for filename in uploaded.keys():
    filepath = os.path.join('known_students', filename)
    with open(filepath, 'wb') as f:
        f.write(uploaded[filename])
    uploaded_files[filename] = filepath

# Load all student images
results = attendance_system.load_all_students(uploaded_files)

# Display loaded students
if attendance_system.known_face_names:
    print("\n✅ Registered Students:")
    for i, name in enumerate(attendance_system.known_face_names, 1):
        print(f"   {i}. {name}")

"""## 📸 Step 5: Upload Classroom Photo

Upload the classroom image containing students you want to recognize.
"""

print("📸 Please upload the classroom photo...\n")

# Upload classroom image
classroom_uploaded = files.upload()

# Get the classroom image path
classroom_filename = list(classroom_uploaded.keys())[0]
classroom_path = f"classroom_{classroom_filename}"

# Save classroom image
with open(classroom_path, 'wb') as f:
    f.write(classroom_uploaded[classroom_filename])

print(f"\n✅ Classroom image uploaded: {classroom_filename}")

"""## 🎯 Step 6: Recognize Students and Mark Attendance

This will:
- Detect all faces in the classroom image
- Match them with registered students
- Generate attendance report
"""

# Recognize students (adjust tolerance if needed: 0.6 is default, lower = stricter)
attendance_data, message = attendance_system.recognize_classroom(classroom_path, tolerance=0.5)

print(message)

if attendance_data:
    # Print summary
    print("\n" + "="*60)
    print("📊 ATTENDANCE SUMMARY")
    print("="*60)
    print(f"📅 Date: {attendance_data['date']}")
    print(f"🕐 Time: {attendance_data['time']}")
    print(f"\n👥 Total Students: {attendance_data['total_students']}")
    print(f"✅ Present: {attendance_data['present_count']}")
    print(f"❌ Absent: {attendance_data['absent_count']}")

    if attendance_data['unknown_faces'] > 0:
        print(f"❓ Unknown Faces: {attendance_data['unknown_faces']}")

    attendance_rate = (attendance_data['present_count'] / attendance_data['total_students']) * 100
    print(f"\n📈 Attendance Rate: {attendance_rate:.1f}%")

    print(f"\n✅ Present Students ({attendance_data['present_count']}):")
    for i, student in enumerate(attendance_data['present'], 1):
        # Find confidence for this student
        confidence = next((d['confidence'] for d in attendance_data['face_details']
                          if d['name'] == student), 0)
        print(f"   {i}. {student} (Confidence: {confidence:.2%})")

    if attendance_data['absent']:
        print(f"\n❌ Absent Students ({attendance_data['absent_count']}):")
        for i, student in enumerate(attendance_data['absent'], 1):
            print(f"   {i}. {student}")

    print("="*60)

"""## 📊 Step 7: Visualize Results"""

if attendance_data:
    # Display annotated classroom image
    plt.figure(figsize=(16, 12))
    plt.imshow(attendance_data['annotated_image'])
    plt.axis('off')
    plt.title('Recognized Students in Classroom', fontsize=16, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.savefig('annotated_classroom.jpg', dpi=150, bbox_inches='tight')
    plt.show()

    print("\n💾 Annotated image saved as 'annotated_classroom.jpg'")

if attendance_data:
    # Create attendance visualization
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Pie chart for attendance
    colors = ['#4CAF50', '#F44336', '#FFC107']
    labels = ['Present', 'Absent']
    sizes = [attendance_data['present_count'], attendance_data['absent_count']]

    if attendance_data['unknown_faces'] > 0:
        labels.append('Unknown')
        sizes.append(attendance_data['unknown_faces'])

    ax1.pie(sizes, labels=labels, colors=colors[:len(sizes)], autopct='%1.1f%%',
            startangle=90, textprops={'fontsize': 12, 'weight': 'bold'})
    ax1.set_title('Attendance Distribution', fontsize=14, fontweight='bold')

    # Bar chart for student status
    categories = ['Present', 'Absent']
    counts = [attendance_data['present_count'], attendance_data['absent_count']]
    bars = ax2.bar(categories, counts, color=['#4CAF50', '#F44336'])
    ax2.set_ylabel('Number of Students', fontsize=12, fontweight='bold')
    ax2.set_title('Attendance Count', fontsize=14, fontweight='bold')
    ax2.set_ylim(0, max(counts) + 2)

    # Add value labels on bars
    for bar in bars:
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height,
                f'{int(height)}',
                ha='center', va='bottom', fontsize=12, fontweight='bold')

    plt.tight_layout()
    plt.savefig('attendance_charts.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("\n💾 Charts saved as 'attendance_charts.png'")

"""## 💾 Step 8: Export Attendance Report"""

if attendance_data:
    # Save CSV report
    csv_filename = attendance_system.save_attendance_csv(attendance_data)
    print(f"\n✅ Attendance report saved: {csv_filename}")

    # Display as DataFrame
    df = pd.read_csv(csv_filename)
    print("\n📋 Attendance Report:")
    display(df)

    # Download CSV
    print("\n⬇️ Downloading CSV file...")
    files.download(csv_filename)

# Download annotated image
if attendance_data:
    print("⬇️ Downloading annotated classroom image...")
    files.download('annotated_classroom.jpg')

    print("\n⬇️ Downloading attendance charts...")
    files.download('attendance_charts.png')

    print("\n✅ All files ready for download!")

"""## ⚙️ Advanced Options (Optional)

### Adjust Recognition Tolerance

If you're getting incorrect matches or missing students, try adjusting the tolerance:
- **Lower tolerance** (e.g., 0.4-0.5): More strict, fewer false positives
- **Higher tolerance** (e.g., 0.7-0.8): More lenient, may catch more students but risk false positives

Default is 0.6
"""

# Re-run recognition with custom tolerance
custom_tolerance = 0.5  # Change this value (0.3 to 0.9)

print(f"🔄 Re-running recognition with tolerance: {custom_tolerance}\n")

attendance_data_custom, message = attendance_system.recognize_classroom(
    classroom_path,
    tolerance=custom_tolerance
)

if attendance_data_custom:
    print("\n" + "="*60)
    print(f"📊 ATTENDANCE SUMMARY (Tolerance: {custom_tolerance})")
    print("="*60)
    print(f"✅ Present: {attendance_data_custom['present_count']}")
    print(f"❌ Absent: {attendance_data_custom['absent_count']}")
    print(f"❓ Unknown: {attendance_data_custom['unknown_faces']}")
    print("="*60)

    # Show the new annotated image
    plt.figure(figsize=(16, 12))
    plt.imshow(attendance_data_custom['annotated_image'])
    plt.axis('off')
    plt.title(f'Recognized Students (Tolerance: {custom_tolerance})',
              fontsize=16, fontweight='bold', pad=20)
    plt.show()

"""## 💡 Tips for Better Results

### For Student Photos:
- ✅ Use clear, front-facing photos
- ✅ Good lighting (avoid shadows on face)
- ✅ One face per image
- ✅ Similar to how they appear in classroom
- ❌ Avoid blurry or low-quality images
- ❌ Avoid extreme angles or partial faces

### For Classroom Photos:
- ✅ High resolution images work best
- ✅ Faces should be clearly visible
- ✅ Good lighting conditions
- ❌ Avoid photos where faces are too small
- ❌ Avoid heavy occlusion (masks, hands covering faces)

### Tolerance Settings:
- **0.4-0.5**: Very strict - Use when students look very different
- **0.6**: Default - Good balance for most cases
- **0.7-0.8**: More lenient - Use when students look similar

---

## 🎉 That's it! You now have a working classroom attendance system!

**What you can do:**
1. ✅ Automatically recognize students from classroom photos
2. ✅ Generate detailed attendance reports
3. ✅ Export data as CSV for record keeping
4. ✅ Visualize attendance with charts and graphs

**Need to start over?** Simply run the cells again from Step 4.

"""